import addDaysToDate from "./add-days-to-date.js";
import addHoursToDate from "./add-hours-to-date.js";
import addMinutesToDate from "./add-minutes-to-date.js";
import addMonthsToDate from "./add-months-to-date.js";
import addSecondsToDate from "./add-seconds-to-date.js";
import addYearsToDate from "./add-years-to-date.js";
import capitalize from "./capitalize.js";
import clamp from "./clamp.js";
import discountedPrice from "./discounted-price.js";
import formatMoney from "./format-money.js";
import fromMinorUnits from "./from-minor-units.js";
import generateRandomString from "./generate-random-string.js";
import generateSequentialString from "./generate-sequential-string.js";
import getAAnForWord from "./get-a-an-for-word.js";
import getAge from "./get-age.js";
import getDateDayDiff from "./get-date-day-diff.js";
import getDateFullText from "./get-date-full-text.js";
import getDateTimeAgo from "./get-date-time-ago.js";
import getDayText from "./get-day-text.js";
import getEndOfDayDate from "./get-end-of-day-date.js";
import getFirstDayOfMonthDate from "./get-first-day-of-month-date.js";
import getFirstDayOfQuarterDate from "./get-first-day-of-quarter-date.js";
import getFirstDayOfWeekDate from "./get-first-day-of-week-date.js";
import getFirstDayOfYearDate from "./get-first-day-of-year-date.js";
import getFormattedDateString from "./get-formatted-date-string.js";
import getFormattedTimeString from "./get-formatted-time-string.js";
import getInitials from "./get-initials.js";
import getLastDayOfMonthDate from "./get-last-day-of-month-date.js";
import getMonthDiff from "./get-month-diff.js";
import getOrdinalSuffix from "./get-ordinal-suffix.js";
import getPaginationParameters from "./get-pagination-parameters.js";
import getShortTextDate from "./get-short-text-date.js";
import getShortTextDayMonthOptionalyear from "./get-short-text-day-month-optionalyear.js";
import getStartOfDayDate from "./get-start-of-day-date.js";
import isString from "./is-string.js";
import isValidEmail from "./is-valid-email.js";
import isWeekend from "./is-weekend.js";
import normalizePhoneNumber from "./normalize-phone-number.js";
import percentageChange from "./percentage-change.js";
import roundOff2Dp from "./round-off-2-dp.js";
import slugify from "./slugify.js";
import splitCompoundString from "./split-compound-string.js";
import textSubtract from "./text-subtract.js";
import toMinorUnits from "./to-minor-units.js";
import toTitleCase from "./to-title-case.js";
import trimAndLowercase from "./trim-and-lowercase.js";
import trimAndUppercase from "./trim-and-uppercase.js";
import truncate from "./truncate.js";
export { addDaysToDate, addHoursToDate, addMinutesToDate, addMonthsToDate, addSecondsToDate, addYearsToDate, capitalize, clamp, discountedPrice, formatMoney, fromMinorUnits, generateRandomString, generateSequentialString, getAAnForWord, getAge, getDateDayDiff, getDateFullText, getDateTimeAgo, getDayText, getEndOfDayDate, getFirstDayOfMonthDate, getFirstDayOfQuarterDate, getFirstDayOfWeekDate, getFirstDayOfYearDate, getFormattedDateString, getFormattedTimeString, getInitials, getLastDayOfMonthDate, getMonthDiff, getOrdinalSuffix, getPaginationParameters, getShortTextDate, getShortTextDayMonthOptionalyear, getStartOfDayDate, isString, isValidEmail, isWeekend, normalizePhoneNumber, percentageChange, roundOff2Dp, slugify, splitCompoundString, textSubtract, toMinorUnits, toTitleCase, trimAndLowercase, trimAndUppercase, truncate, };
declare const _default: {
    addDaysToDate: (days: number, date?: Date) => Date;
    addHoursToDate: (hours: number, date?: Date) => Date;
    addMinutesToDate: (minutes: number, date?: Date) => Date;
    addMonthsToDate: (months: number, date?: Date) => Date;
    addSecondsToDate: (seconds: number, date?: Date) => Date;
    addYearsToDate: (years: number, date?: Date) => Date;
    capitalize: (text: string) => string;
    clamp: (value: number, min: number, max: number) => number;
    discountedPrice: (value: number, discountAmount?: number, discountPercent?: number) => number;
    formatMoney: (amount: number, currencySymbol?: string, minimumFractionDigits?: number, maximumFractionDigits?: number) => string;
    fromMinorUnits: (minorUnits: number) => number;
    generateRandomString: (length?: number, charset?: string) => string;
    generateSequentialString: (serialNumber: number, outputLength?: number, charset?: string) => string;
    getAAnForWord: (word: string) => "a" | "an";
    getAge: (birthDate: Date | string | number, asOf?: Date) => number;
    getDateDayDiff: (date: Date, anotherDate: Date) => number;
    getDateFullText: (timestampOrdateOrDateString: number | string | Date) => string;
    getDateTimeAgo: (dateStart: string | number | Date, dateEnd?: string | number | Date) => string;
    getDayText: (timestampOrdateOrDateString: number | string | Date) => string;
    getEndOfDayDate: (daysAgo?: number, date?: Date) => Date;
    getFirstDayOfMonthDate: (date?: Date) => Date;
    getFirstDayOfQuarterDate: (date?: Date) => Date;
    getFirstDayOfWeekDate: (date?: Date) => Date;
    getFirstDayOfYearDate: (date?: Date) => Date;
    getFormattedDateString: (timestampOrdateOrDateString: number | string | Date) => string;
    getFormattedTimeString: (dateOrDateString: string | Date | number) => string;
    getInitials: (name: string, max?: number) => string;
    getLastDayOfMonthDate: (date?: Date) => Date;
    getMonthDiff: (dateFrom: Date, dateTo: Date) => number;
    getOrdinalSuffix: (value: number) => string;
    getPaginationParameters: (page: number, limit: number) => {
        toSkip: number;
        limit: number;
    };
    getShortTextDate: (timestampOrdateOrDateString: number | string | Date) => string;
    getShortTextDayMonthOptionalyear: (timestampOrdateOrDateString: number | string | Date) => string;
    getStartOfDayDate: (daysAgo?: number, date?: Date) => Date;
    isString: (x: unknown) => boolean;
    isValidEmail: (value: string) => boolean;
    isWeekend: (date?: Date) => boolean;
    normalizePhoneNumber: (phoneNumber: string, countryCode?: string) => string;
    percentageChange: (from: number, to: number) => number;
    roundOff2Dp: (number: number) => number;
    slugify: (text: string) => string;
    splitCompoundString: (compoundString: string) => [string, string];
    textSubtract: (text: string, subtractLength: number, startIndex?: number, removeExtraSpace?: boolean) => string;
    toMinorUnits: (amount: number) => number;
    toTitleCase: (text: string) => string;
    trimAndLowercase: (text: string) => string;
    trimAndUppercase: (text: string) => string;
    truncate: (text: string, maxLength: number, suffix?: string) => string;
};
export default _default;
//# sourceMappingURL=index.d.ts.map